### ISSUE TITLE
Question, not issue...

### ISSUE THREAD

**Issue by rchrdnsh** [lukewestby/elm-synth#2]
Hi Luke,

This is a great start, but as I was looking through the code it struck me that I could not find the actually signal processing algorithms for the waveforms themselves...sooooo...where is the actual code that describes and produces the actual waveforms themselves, in other words, there signal creation and processing?

Thank you for your time :-)

R

**Comment by lukewestby** [comment]
Hey!

It's all right here:

https://github.com/lukewestby/elm-synth/blob/master/index.html#L13-L40

Not a whole lot going on, the Web Audio API does a lot for us :)
